class OrchestrationContext: ...
class HttpRequest:
    @property
    def url(self) -> str: ...
class HttpResponse:
    def __init__(body=None, *, status_code=None, headers=None, mimetype=None, charset=None): ...

# look into azure func implementations to complete stubs