# CI pipeline for master branch commits:
# * builds python package
# * publishes python package
###########################################################################
# Requires the following varibles to be defined for the pipeline on the ADO UI
#  - baseFolder 
#  - componentArtifactName (added to the script)
###########################################################################

trigger: 
  branches:
    include:
    - master


variables:     
  agentPool: 'ubuntu-latest' # 'Ubuntu-16.04'
  python.version: '3.6'
  ##pypiFeed: 
  baseFolder: .
  componentArtifactName: 'azure_functions_durable'
  

stages:
- stage: Build
  displayName: Build PyPi Artifact
  jobs:

  - job: Build_Durable_Functions
    displayName: Build Python Package
    pool: 
      vmImage: $(agentPool)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install wheel
      workingDirectory: $(baseFolder) 
      displayName: 'Install dependencies'

    - script: |
        python setup.py clean --all
        python setup.py build
      displayName: 'Autogenerate gRPC Python files'

    - script: |
        python setup.py sdist bdist bdist_wheel
      workingDirectory: $(baseFolder) 
      displayName: 'Building'

    - script: |
        cd azure
        flake8 . --count --show-source --statistics
      displayName: 'Run lint test with flake8'

    - script: |
        pip install pytest pytest-azurepipelines
        pytest
      displayName: 'pytest'

    - upload: dist
      displayName: 'Publish Build Artifacts'
      artifact: $(componentArtifactName)
