# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DurableFunctions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DurableFunctions.proto',
  package='gRPCChannel',
  syntax='proto3',
  serialized_options=_b('\252\002\020DurableTask.GRpc'),
  serialized_pb=_b('\n\x16\x44urableFunctions.proto\x12\x0bgRPCChannel\"-\n\x15NewDurableTaskRequest\x12\x14\n\x0c\x66unctionName\x18\x01 \x01(\t\"\xa9\x01\n\x16NewDurableTaskResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x19\n\x11StatusQueryGetUri\x18\x02 \x01(\t\x12\x18\n\x10SendEventPostUri\x18\x03 \x01(\t\x12\x18\n\x10TerminatePostUri\x18\x04 \x01(\t\x12\x15\n\rRewindPostUri\x18\x05 \x01(\t\x12\x1d\n\x15PurgeHistoryDeleteUri\x18\x06 \x01(\t2i\n\x12\x44urableTaskService\x12S\n\x08StartNew\x12\".gRPCChannel.NewDurableTaskRequest\x1a#.gRPCChannel.NewDurableTaskResponseB\x13\xaa\x02\x10\x44urableTask.GRpcb\x06proto3')
)




_NEWDURABLETASKREQUEST = _descriptor.Descriptor(
  name='NewDurableTaskRequest',
  full_name='gRPCChannel.NewDurableTaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='functionName', full_name='gRPCChannel.NewDurableTaskRequest.functionName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=84,
)


_NEWDURABLETASKRESPONSE = _descriptor.Descriptor(
  name='NewDurableTaskResponse',
  full_name='gRPCChannel.NewDurableTaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='gRPCChannel.NewDurableTaskResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='StatusQueryGetUri', full_name='gRPCChannel.NewDurableTaskResponse.StatusQueryGetUri', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SendEventPostUri', full_name='gRPCChannel.NewDurableTaskResponse.SendEventPostUri', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TerminatePostUri', full_name='gRPCChannel.NewDurableTaskResponse.TerminatePostUri', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RewindPostUri', full_name='gRPCChannel.NewDurableTaskResponse.RewindPostUri', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PurgeHistoryDeleteUri', full_name='gRPCChannel.NewDurableTaskResponse.PurgeHistoryDeleteUri', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=256,
)

DESCRIPTOR.message_types_by_name['NewDurableTaskRequest'] = _NEWDURABLETASKREQUEST
DESCRIPTOR.message_types_by_name['NewDurableTaskResponse'] = _NEWDURABLETASKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewDurableTaskRequest = _reflection.GeneratedProtocolMessageType('NewDurableTaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _NEWDURABLETASKREQUEST,
  '__module__' : 'DurableFunctions_pb2'
  # @@protoc_insertion_point(class_scope:gRPCChannel.NewDurableTaskRequest)
  })
_sym_db.RegisterMessage(NewDurableTaskRequest)

NewDurableTaskResponse = _reflection.GeneratedProtocolMessageType('NewDurableTaskResponse', (_message.Message,), {
  'DESCRIPTOR' : _NEWDURABLETASKRESPONSE,
  '__module__' : 'DurableFunctions_pb2'
  # @@protoc_insertion_point(class_scope:gRPCChannel.NewDurableTaskResponse)
  })
_sym_db.RegisterMessage(NewDurableTaskResponse)


DESCRIPTOR._options = None

_DURABLETASKSERVICE = _descriptor.ServiceDescriptor(
  name='DurableTaskService',
  full_name='gRPCChannel.DurableTaskService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=258,
  serialized_end=363,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartNew',
    full_name='gRPCChannel.DurableTaskService.StartNew',
    index=0,
    containing_service=None,
    input_type=_NEWDURABLETASKREQUEST,
    output_type=_NEWDURABLETASKRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DURABLETASKSERVICE)

DESCRIPTOR.services_by_name['DurableTaskService'] = _DURABLETASKSERVICE

# @@protoc_insertion_point(module_scope)
