name: Sync submodule pipeline

on:
  push:
    branches: [ submodule ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: azure/azure-functions-python-library
          submodules: true
          ref: wangbill/add-submodule
      - id: GoToSubmodule
        run: |
          git config --global user.email "azfuncgh@github.com"
          git config --global user.name "Azure Functions"
          # ls azure/functions/durable -ltr
          git submodule status
          # rm -rf azure/functions/durable
          # git submodule update --init --recursive
          # git submodule update --remote --merge
          git submodule foreach git pull --rebase
          git add .
          git commit -m "submodule-sync"
      - name: Create Pull Request
        id: createPullRequest
        uses: peter-evans/create-pull-request@v4
        with:
          branch: submodule-sync
          delete-branch: true
          title: 'Update durable submodule'
          body: |
            Updated submodule

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            required submodule update
            automated pr
          reviewers: vameru
      - name: Check outputs
        run: |
            echo "Pull Request Number - ${{ steps.createPullRequest.outputs.pull-request-number }}"
            echo "Pull Request URL - ${{ steps.createPullRequest.outputs.pull-request-url }}"
