name: Empty Workflow

on:
  push:
    branches:
      - main
      - dev
      - dajusto/add-gh-actions-tests
  pull_request:
    branches:
      - main
      - dev
      - dajusto/add-gh-actions-tests

jobs:
  empty_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Empty step
        run: echo "This is an empty GitHub Actions workflow."